// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef __futureheatwaves_h__
#define __futureheatwaves_h__

#include "futureheatwaves_RcppExports.h"

#endif // __futureheatwaves_h__
