// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// IDHeatwavesCPP
DataFrame IDHeatwavesCPP(int heatwaveLength, NumericVector tempsExceedingCutoff);
RcppExport SEXP futureheatwaves_IDHeatwavesCPP(SEXP heatwaveLengthSEXP, SEXP tempsExceedingCutoffSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type heatwaveLength(heatwaveLengthSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tempsExceedingCutoff(tempsExceedingCutoffSEXP);
    __result = Rcpp::wrap(IDHeatwavesCPP(heatwaveLength, tempsExceedingCutoff));
    return __result;
END_RCPP
}
