// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/futureheatwaves.h"
#include <Rcpp.h>
#include <string>
#include <set>

using namespace Rcpp;

// IDHeatwavesCPP
Rcpp::DataFrame IDHeatwavesCPP(int heatwaveLength, Rcpp::NumericVector tempsExceedingCutoff);
static SEXP futureheatwaves_IDHeatwavesCPP_try(SEXP heatwaveLengthSEXP, SEXP tempsExceedingCutoffSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< int >::type heatwaveLength(heatwaveLengthSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type tempsExceedingCutoff(tempsExceedingCutoffSEXP);
    rcpp_result_gen = Rcpp::wrap(IDHeatwavesCPP(heatwaveLength, tempsExceedingCutoff));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP futureheatwaves_IDHeatwavesCPP(SEXP heatwaveLengthSEXP, SEXP tempsExceedingCutoffSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(futureheatwaves_IDHeatwavesCPP_try(heatwaveLengthSEXP, tempsExceedingCutoffSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// storeHeatwaveEntry
void storeHeatwaveEntry(int index, int hwSize, int hwCounter, std::vector<int>& hw, std::vector<int>& hwNumber);
static SEXP futureheatwaves_storeHeatwaveEntry_try(SEXP indexSEXP, SEXP hwSizeSEXP, SEXP hwCounterSEXP, SEXP hwSEXP, SEXP hwNumberSEXP) {
BEGIN_RCPP
    Rcpp::traits::input_parameter< int >::type index(indexSEXP);
    Rcpp::traits::input_parameter< int >::type hwSize(hwSizeSEXP);
    Rcpp::traits::input_parameter< int >::type hwCounter(hwCounterSEXP);
    Rcpp::traits::input_parameter< std::vector<int>& >::type hw(hwSEXP);
    Rcpp::traits::input_parameter< std::vector<int>& >::type hwNumber(hwNumberSEXP);
    storeHeatwaveEntry(index, hwSize, hwCounter, hw, hwNumber);
    return R_NilValue;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP futureheatwaves_storeHeatwaveEntry(SEXP indexSEXP, SEXP hwSizeSEXP, SEXP hwCounterSEXP, SEXP hwSEXP, SEXP hwNumberSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(futureheatwaves_storeHeatwaveEntry_try(indexSEXP, hwSizeSEXP, hwCounterSEXP, hwSEXP, hwNumberSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// storeZeroes
void storeZeroes(int index, int potentialHeatwave, std::vector<int>& hw, std::vector<int>& hwNumber);
static SEXP futureheatwaves_storeZeroes_try(SEXP indexSEXP, SEXP potentialHeatwaveSEXP, SEXP hwSEXP, SEXP hwNumberSEXP) {
BEGIN_RCPP
    Rcpp::traits::input_parameter< int >::type index(indexSEXP);
    Rcpp::traits::input_parameter< int >::type potentialHeatwave(potentialHeatwaveSEXP);
    Rcpp::traits::input_parameter< std::vector<int>& >::type hw(hwSEXP);
    Rcpp::traits::input_parameter< std::vector<int>& >::type hwNumber(hwNumberSEXP);
    storeZeroes(index, potentialHeatwave, hw, hwNumber);
    return R_NilValue;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP futureheatwaves_storeZeroes(SEXP indexSEXP, SEXP potentialHeatwaveSEXP, SEXP hwSEXP, SEXP hwNumberSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(futureheatwaves_storeZeroes_try(indexSEXP, potentialHeatwaveSEXP, hwSEXP, hwNumberSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}

// validate (ensure exported C++ functions exist before calling them)
static int futureheatwaves_RcppExport_validate(const char* sig) { 
    static std::set<std::string> signatures;
    if (signatures.empty()) {
        signatures.insert("Rcpp::DataFrame(*IDHeatwavesCPP)(int,Rcpp::NumericVector)");
        signatures.insert("void(*storeHeatwaveEntry)(int,int,int,std::vector<int>&,std::vector<int>&)");
        signatures.insert("void(*storeZeroes)(int,int,std::vector<int>&,std::vector<int>&)");
    }
    return signatures.find(sig) != signatures.end();
}

// registerCCallable (register entry points for exported C++ functions)
RcppExport SEXP futureheatwaves_RcppExport_registerCCallable() { 
    R_RegisterCCallable("futureheatwaves", "futureheatwaves_IDHeatwavesCPP", (DL_FUNC)futureheatwaves_IDHeatwavesCPP_try);
    R_RegisterCCallable("futureheatwaves", "futureheatwaves_storeHeatwaveEntry", (DL_FUNC)futureheatwaves_storeHeatwaveEntry_try);
    R_RegisterCCallable("futureheatwaves", "futureheatwaves_storeZeroes", (DL_FUNC)futureheatwaves_storeZeroes_try);
    R_RegisterCCallable("futureheatwaves", "futureheatwaves_RcppExport_validate", (DL_FUNC)futureheatwaves_RcppExport_validate);
    return R_NilValue;
}
