#' Apply a function across all projections
#'
#' This function will take a user-specified function and apply it across
#' all the heatwave projection data files output by \code{\link{gen_hw_set}}.
#' It will generate either a single value for every ensemble member within
#' every climate model, if \code{city_specific} is set to \code{FALSE}, or
#' a value for every community for every ensemble member, if
#' \code{city_specific} is set to \code{TRUE}.
#'
#' @param FUN A character string giving the name of a function to apply to
#'    the heatwave dataframe located in the file specified by \code{hwPath}.
#'    This function must only take one argument, \code{hw_datafr}, which
#'    identifies a dataframe as generated by \code{\link{gen_hw_set}},
#'    with the columns for staring and ending dates in the Date class,
#'    the column for the city as a factor, and all other columns as
#'    numeric class. The function should output a single value when
#'    applied to the full dataframe.
#' @param city_specific TRUE / FALSE: Should the function be calculated
#'    separately for each community within the dataframe?
#' @inheritParams gen_hw_set
#'
#' @return A dataframe with the value output by the user-specified
#'    function, as applied to every dataframe of heatwaves and characteristics
#'    for every ensemble member of every climate model.
#'
#' @export
apply_all_models <- function(out, FUN, city_specific = FALSE){

        proj_files <- list.files(paste(out, "Heatwaves", sep = "/"),
                                 recursive = TRUE, full.names = TRUE)

        result_list <- lapply(proj_files,
                              apply_hw_projections,
                              FUN,
                              city_specific)
        result_df <- do.call(rbind.data.frame, result_list)

        return(result_df)
}

#' Apply a function to projected heatwaves
#'
#' This function takes a user-specified function and applies is to a
#' single file of heatwave projections, as specified by \code{hwPath}.
#'
#' @param hwPath A filepath to a comma-separated (csv) file with a dataset
#'    of heatwaves and their characteristics, as generated by
#'    \code{\link{gen_hw_set}}. The file at the specified filepath must
#'    exactly conform to the format of the heatwave files created by
#'    \code{\link{gen_hw_set}}.
#' @inheritParams apply_all_models
#'
#' @note The function input as \code{FUN} must follow a very specific
#'    structure. It most have only one argument, and that argument
#'    must be a dataframe with heatwaves and their characteristics, as
#'    generated by the \code{\link{gen_hw_set}} function.
#'
#' @export
#'
#' @importFrom dplyr %>%
apply_hw_projections <- function(hwPath, FUN, city_specific = FALSE){

        hwPathSplit <- unlist(strsplit(hwPath, split = "/"))
        modelName <- hwPathSplit[(length(hwPathSplit) - 1)]
        ensembleName <- sub(".csv", "", hwPathSplit[length(hwPathSplit)])

        hw_datafr <- utils::read.csv(hwPath, as.is = TRUE) %>%
                dplyr::mutate_(city = ~ factor(city),
                       start.date = ~ as.Date(start.date),
                       end.date = ~ as.Date(end.date))

        if(!city_specific){
                hw_fun_out <- do.call(FUN, list(hw_datafr = hw_datafr))
                hw_fun_out <- data.frame(model = modelName,
                                         ensemble = ensembleName,
                                         value = hw_fun_out)
        } else {
                cities <- levels(hw_datafr$city)
                hw_fun_out <- data.frame(model = modelName,
                                         ensemble = ensembleName,
                                         city = cities,
                                         value = NA)
                for(i in 1:length(cities)){
                        hw_datafr_city <- dplyr::filter_(hw_datafr,
                                                        ~ city == cities[i])
                        hw_fun_out$value[i] <- do.call(FUN,
                                                list(hw_datafr = hw_datafr_city))
                }
        }
        return(hw_fun_out)
}

