#' Create heatwave dataframe for the given ensemble
#'
#' @param ensemble Character string that gives the absolute file path
#'    for the directory with a particular ensemble member of a climate
#'    model projection.
#' @param thresholds Vector of community-specific thresholds to use in
#'    identifying heatwaves.
#' @param global An object name for the 'global' variable list. This
#'    parameter is passed through from \code{gen_hw_set} and includes user
#'    specifications for the path to the output directory, the path to the
#'    input climate projections, the dataframe with community locations, the
#'    format for the filenames of the coordinate, tas, and time files in the
#'    ensemble-specific subdirectories of the projection directory input by
#'    the user, and whether the user prefers to run the function using the R
#'    or C++ version of the function to identify heatwaves.
#' @param custom An object name for the 'custom` data list. This parameter is
#'    passed through from \code{gen_hw_set} and includes user specifications
#'    for, if specified as other than the default, an alternative function to
#'    use to identify heatwaves, alternative upper and lower year boundaries
#'    for the projection period of the heatwave datasets being generated,
#'    alternative upper and lower year boundaries for the reference period
#'    to be used when measuring all heatwave characteristics related to
#'    relative, rather than absolute, temperature, and the percentile
#'    threshold to use when defining heatwaves.
#'
#' @return The combined dataframe of identified heatwaves for all cities of
#'    the given ensemble.
formHwFrame <- function(ensemble, thresholds, global, custom){
        # Acquire list of heatwave dataframes for each city
        hwDataframeList <- apply(data.frame(thresholds), 1,
                                 createCityProcessor(global),
                                 ensemble, custom)

        # Combine the heatwave dataframes contained in hwDataframeList into
        # a single dataframe
        hwFrame <- consolidate(hwDataframeList)

        return(hwFrame)
}

#' Identify and aggregate heatwaves for a particular city
#'
#' @param global List of global parameters generated by listGlobal.
#' @param custom List of custom parameters generated by listCustom.
#'
#' @return A closure that will find all heatwaves for a given ensemble. Each passed threshold corresponds to a particular
#' city. The closure advances an incrementer every time it is called to get this effect.
#' Argument 1: A threshold temperature
#' Argument 2: The ensemble from which you wish to find heatwaves.
#'
#' @note The closure encapsulates an incrementer varaible and advances it with every call. This variable is used to
#' index into the cities vector from the "global" data list.
# TODO: There is a redefinition of the custom variable. Test if it is necessary.
# TODO: Add documentation of the format of the return value
# TODO: Eventually, figure out if there is an elegant way of getting the corresponding city without the need for a closure
# to increment over the cities list.
createCityProcessor <- function(global, custom){

        # incrementer
        i <- 1

        function(threshold, ensemble, custom){
                city <- as.character(global$cities[i,1])
                cat("Creating heatwave dataframe ~~ City: ", city, " ~~ City Number: ", i, " ~~ Cutoff: ", threshold, "\n")

                datafr <- data.frame(ensemble$dates, ensemble$series[,i])

                # Identify all heatwaves for the given city
                heatwaves <- IDheatwaves(city, threshold, 2, datafr, global, custom)

                # Aggregate heatwaves for the given city
                hwDataframeList <- createHwDataframe(city = city, threshold = threshold, heatwaves = heatwaves, ensemble = ensemble, i = i, global = global, custom = custom)

                i <<- i + 1
                return(hwDataframeList)
        }
}

#' Combine all identified heatwave dataframes together into one.
#'
#' @param A list of identified heatwave dataframes created by the closure of createCityProcessor
#'
#' @return A combined dataframe of identified heatwave dataframes from the dataframe list that was passed as an argument.
consolidate <- function(hwDataframeList){
        all <- hwDataframeList[[1]]
        for(i in 2:length(hwDataframeList)){
                all <- rbind(all, hwDataframeList[[i]])
        }
        return(all)
}



#' Aggregate by heatwave
#'
#' @param city Index of cities global
#' @param threshold Threshold temperature for this city
#' @param heatwaves data.frame(dates, thresholds)
#' @param percentile Percentile for threshold)
#'
#' @return Result is a dataframe where each row represents a heatwave.
#'
#' @importFrom dplyr %>%
createHwDataframe <- function(city = stop("Unspecified city"),
                              threshold = stop("Unspecified threshold"),
                              heatwaves = stop("'heatwaves' unspecified"),
                              percentile = .98,
                              ensemble,
                              i,
                              global, custom){
        hold <<- heatwaves

        intermediate <- heatwaves
        heatwaves2 <- subset(intermediate, hw == 1)

        if(custom["createHwDataframe"] != FALSE){
                datafr <- data.frame(ensemble$dates, ensemble$reference[,i])
                heatwaves <- IDheatwaves(city, threshold, 2, datafr,
                                         global, custom)
        }

        bloodhound <<- heatwaves2
        bark <<- heatwaves

        hw.frame <- dplyr::group_by(heatwaves2, hw.number) %>%
                dplyr::summarize(mean.temp = mean(tmpd),
                                 max.temp = max(tmpd),
                                 min.temp = min(tmpd),
                                 length = length(unique(date)),
                                 start.date = date[1],
                                 end.date = date[length(date)],
                                 start.doy = as.POSIXlt(date[1])$yday,
                                 start.month = as.POSIXlt(date[1])$mon + 1,
                                 days.above.80 = length(date[tmpd > 80]),
                                 days.above.85 = length(date[tmpd > 85]),
                                 days.above.90 = length(date[tmpd > 90]),
                                 days.above.95 = length(date[tmpd > 95]),
                                 days.above.99th = length(date[tmpd > quantile(heatwaves$tmpd, .99, na.rm = TRUE)]),
                                 days.above.99.5th = length(date[tmpd > quantile(heatwaves$tmpd, .995, na.rm = TRUE)]))

        hw.frame$first.in.season <- c(1, rep(NA, nrow(hw.frame) - 1))
        for(i in 2:nrow(hw.frame)){
                if(as.POSIXlt(hw.frame$start.date)$year[i] !=
                   as.POSIXlt(hw.frame$start.date)$year[i - 1]){
                        hw.frame$first.in.season[i] <- 1
                } else {
                        hw.frame$first.in.season[i] <- 0
                }
        }

        hw.frame$"98th.temp" <- threshold

        dist.tmpd <- ecdf(heatwaves$tmpd)
        hw.frame$mean.temp.quantile <- dist.tmpd(hw.frame$mean.temp)
        hw.frame$max.temp.quantile <- dist.tmpd(hw.frame$max.temp)
        hw.frame$min.temp.quantile <- dist.tmpd(hw.frame$min.temp)

        hw.frame$mean.temp.1 <- mean(heatwaves$tmpd)
        summertime <- as.POSIXlt(heatwaves$date)$mon %in% c(4:8)
        hw.frame$mean.summer.temp <- mean(heatwaves$tmpd[summertime])

        hw.frame$city <- city

        return(hw.frame)
}

