# TODO: clarify documentation. Do this after testing.

#' Process valid models
#'
#' This function takes any models that are valid, identifies and characterizes
#'    heatwaves within projections for each of its ensemble members, writes
#'    those dataframes of heatwave projections out to the user-specified output
#'    directory, and stores information about the models that have been written
#'    to the output directory using the closure, \code{accumulators}, created by
#'    \code{createAccumulators}.
#'
#' @param model List with parsed information about the directory structure for
#'    a specific climate model from the user-specified projections directory.
#'    This list is a subset of the list generated by
#'    \code{acquireDirectoryStructure}.
#' @param global An object name for the 'global' variable list. This
#'    parameter is passed through from \code{gen_hw_set} and includes user
#'    specifications for the path to the output directory, the path to the
#'    input climate projections, the dataframe with community locations, the
#'    format for the filenames of the coordinate, tas, and time files in the
#'    ensemble-specific subdirectories of the projection directory input by
#'    the user, and whether the user prefers to run the function using the R
#'    or C++ version of the function to identify heatwaves.
#' @param custom An object name for the 'custom` data list. This parameter is
#'    passed through from \code{gen_hw_set} and includes user specifications
#'    for, if specified as other than the default, an alternative function to
#'    use to identify heatwaves, alternative upper and lower year boundaries
#'    for the projection period of the heatwave datasets being generated,
#'    alternative upper and lower year boundaries for the reference period
#'    to be used when measuring all heatwave characteristics related to
#'    relative, rather than absolute, temperature, and the percentile
#'    threshold to use when defining heatwaves.
#' @param accumulators An object name for the closure generated by
#'    \code{createAccumulators}.
#'
#' @return A list of rcp 8.5 ensembles for the given model
processModel <- function(model, global, custom, accumulators){

        # Get reference period if one exists
        reference <- custom["processModel"] # referenceBoundaries argument
                                            # from `gen_hw_set`

        # Acquire vector of threshold temperatures using the historical
        # ensemble for this model which possesses the name r1i1p1
        ret <- processHistorical(model, global, custom, reference)
        thresholds <- ret[[1]]
        reference <- ret[[2]]

        # Acquire characteristics of each RCP 8.5 ensemble of the model
        modelName <- model[[1]]
        histens <- model[[2]]
        rcpens <- model[[3]]
        rcpEnsembles <- lapply(rcpens,
                               processRCP,
                               modelName,
                               createEnsembleWriter(modelName, global, custom),
                               thresholds,
                               global,
                               custom,
                               accumulators,
                               reference)

        # Add entry to the modelInfoAccumulator
        accumulators("append model information",
                     data.frame(modelName, length(histens), length(rcpens)))

        return(rcpEnsembles)
}

#' Calculate threshold temperatures
#'
#' This function calculates the threshold temperatures required to identify
#'    heatwaves in the climate projection data using each climate model's
#'    first listed historical ensemble. These values are both used in later
#'    functions to identify heatwaves in the projections and are also saved
#'    to file through this function to have for future reference.
#'
#' @param model List with parsed information about the directory structure for
#'    a specific climate model from the user-specified projections directory.
#'    This list is a subset of the list generated by
#'    \code{acquireDirectoryStructure}.
#' @param global An object name for the 'global' variable list. This
#'    parameter is passed through from \code{gen_hw_set} and includes user
#'    specifications for the path to the output directory, the path to the
#'    input climate projections, the dataframe with community locations, the
#'    format for the filenames of the coordinate, tas, and time files in the
#'    ensemble-specific subdirectories of the projection directory input by
#'    the user, and whether the user prefers to run the function using the R
#'    or C++ version of the function to identify heatwaves.
#' @param custom An object name for the 'custom` data list. This parameter is
#'    passed through from \code{gen_hw_set} and includes user specifications
#'    for, if specified as other than the default, an alternative function to
#'    use to identify heatwaves, alternative upper and lower year boundaries
#'    for the projection period of the heatwave datasets being generated,
#'    alternative upper and lower year boundaries for the reference period
#'    to be used when measuring all heatwave characteristics related to
#'    relative, rather than absolute, temperature, and the percentile
#'    threshold to use when defining heatwaves.
#' @param reference FALSE, if the user has not specified custom reference
#'    boundaries through the \code{referenceBoundaries} argument in
#'    \code{gen_hw_set}, otherwise a vector with four elements
#'    (earliest historical year, latest historical year,
#'    earliest future projection year, latest future projection year)
#'    giving the user-specified custom date boundaries for the
#'    heatwave projections.
#'
#' @return A list with two elements: (1) a vector with one element for
#'    each community included in the user-specified community location
#'    file, with each element value giving the threshold temperature for the
#'    heatwave definition for a community, in the same order that communities
#'    are listed in the user-specificed \code{citycsv} file and (2) a
#'    \code{processModel} object, which is FALSE if the user did not
#'    specify custom year boundaries with \code{dataBoundaries} in
#'    \code{gen_hw_set} and otherwise is ... .
#'    This function also writes threshold temperatures to files within
#'    the user-specified output directory for future reference.
processHistorical <- function(model, global, custom, reference = FALSE){
        name <- model[[1]]

        # To find the threshold, use the first ensemble member within
        # that historical directory
        historicalDirs <- model[[2]][1][[1]]
        cat("Processing historical ensemble for", name, "\n")

        # Acquire characteristics of the first historical ensemble
        historicalEnsemble <- processEnsemble(ensemble = historicalDirs,
                                              experiment = 'historical',
                                              modelName = name,
                                              global = global,
                                              custom = custom,
                                              reference = reference)

        # Calculate threshold temperatures using the user-specified
        # threshold percentile (default: 0.98)
        thresholds <- apply(historicalEnsemble$series, 2, quantile,
                            probs = custom$probThreshold)

        # Acquire the reference series. Will be false if reference period
        # unspecified
        reference_series <- historicalEnsemble$reference

        # Save thresholds to file
        writeThresholds(name, 'thresholds', thresholds, global, custom)

        ret <- list(thresholds, reference_series)
        return(ret)
}

#' Create heatwave dataframe for climate projection
#'
#' For each reference ensemble, create the heatwave dataframe and
#' write it to file. Also store the locations  vector for each ensemble.
#'
#' @param ensemble
#' @param modelName
#' @param ensembleWriter
#' @param thresholds
#' @param global The 'global' variable list.
#' @param custom The user-specified custom data list.
#' @param accumulators Closures ... generated by createAccumulators
#' @param reference [What is this parameter?]
#'
#' @return Write every heatwave dataframe to a .csv and return the ensemble
#'    used as the reference.
processRCP <- function(ensemble, modelName, ensembleWriter, thresholds,
                       global, custom, accumulators, reference = FALSE){
        cat("Processing rcp 8.5 ensemble", modelName, "\n")

        # Acquire desired characteristics of the RCP 8.5 ensembles
        ensemble <- processEnsemble(ensemble, 'rcp', modelName, global,
                                    custom, reference)

        # Append locations vector to the locations vector accumulator
        accumulators("append location list", ensemble$locations)

        # Acquire the heatwave dataframes for every rcp 8.5 ensemble in this model
        hwFrame <- formHwFrame(ensemble, thresholds, global, custom)

        # Write every heatwave frame to a .csv
        ensembleWriter(hwFrame)

        # Return the ensemble used as the reference
        return(ensemble)
}

#' Extract projections from ensemble member
#'
#' This function extract the desired climate data out of a single ensemble
#'    member of the climate model's projections either from a historical or
#'    future projection.
#'
#' To do this, the function (1) reads in the latitude
#'    and longitude data from the grid location file for the ensemble member;
#'    (2) reads in the climate projection data for the ensemble member; (3)
#'    reads in the time file for the ensemble member; (4) finds the closest
#'    grid point in the climate model grid for each community in the
#'    \code{citycsv} file provided by the user; (5) ...
#'
#' @param model List with parsed information about the directory structure for
#'    a specific ensemble member from the user-specified projections directory.
#'    This list is a subset of the list generated by
#'    \code{acquireDirectoryStructure}.
#' @param experiment Character string of the experiment of interest.
#'    Possible variables are "historical" or "rcp85".
#' @param model Character string of climate model name (e.g., "bcc1"). This
#'    name is typically generated for use in this function from the subdirectory
#'    names for the climate model within the directory of projection data
#'    specified by the user in \code{gen_hw_set}.
#' @param global An object name for the 'global' variable list. This
#'    parameter is passed through from \code{gen_hw_set} and includes user
#'    specifications for the path to the output directory, the path to the
#'    input climate projections, the dataframe with community locations, the
#'    format for the filenames of the coordinate, tas, and time files in the
#'    ensemble-specific subdirectories of the projection directory input by
#'    the user, and whether the user prefers to run the function using the R
#'    or C++ version of the function to identify heatwaves.
#' @param custom An object name for the 'custom` data list. This parameter is
#'    passed through from \code{gen_hw_set} and includes user specifications
#'    for, if specified as other than the default, an alternative function to
#'    use to identify heatwaves, alternative upper and lower year boundaries
#'    for the projection period of the heatwave datasets being generated,
#'    alternative upper and lower year boundaries for the reference period
#'    to be used when measuring all heatwave characteristics related to
#'    relative, rather than absolute, temperature, and the percentile
#'    threshold to use when defining heatwaves.
#' @param reference FALSE, if the user has not specified custom reference
#'    boundaries through the \code{referenceBoundaries} or
#'    \code{dataBoundaries} arguments (depending on whether \code{experiment}
#'    is "historical" or "rcp85") in
#'    \code{gen_hw_set}, otherwise a vector with four elements
#'    (earliest historical year, latest historical year,
#'    earliest future projection year, latest future projection year)
#'    giving the user-specified custom date boundaries for the
#'    heatwave projections.
#'
#' @return Returns a list with...
#'
#' @note This function uses the Pythagorean theorem to calculate the distance
#'    between each community given in the \code{citycsv} file and the nearest
#'    grid point for the climate model for the specified ensemble member.
processEnsemble <- function(ensemble, experiment, modelName, global,
                            custom, reference){

        # Read the ensemble data
        cat("Reading --->", ensemble[1], "\n")
        latlong <- readLatLong(ensemble)
        tas <- readtas(ensemble)
        times <- readTimes(ensemble)
        cat("Read operation complete", "\n")

        # Find indices of the closest points of measurement
        locations <- apply(global$cities, 1, closest_point, latlong = latlong)

        # Acquire the boundaries for the time series
        # Structure: c(start index, end index, # of elements spanning
        # from start to end)
        bounds <- getBounds(times = times,
                            experiment = experiment,
                            custom = custom)
        start <- bounds[1]
        end <- bounds[2]

        #         if(debug){
        #                 print("Process Ensemble Bounds: ")
        #                 cat("start: ", start, "\n")
        #                 cat("end: ", end, "\n")
        #         }

        subCustom <- list("IDheatwaves" = FALSE,
                          "getBounds" = reference,
                          "processModel" = FALSE,
                          "createHwDataframe" = FALSE)
        # Get a vector containing the dates of days we are dealing with
        dates <- formDates(times, bounds)

        # Acquire time series for every city
        series <- data.frame(tas[start:end, locations])

        # Convert the time series data to Fahrenheit
        series <- apply(series, 1:2, function(element) {
                return((element * 9/5) - 459.67)
        })

        # CUSTOM BLOCK
        # Extract and store the reference period data
        if(reference != FALSE && length(reference) != 1){
                rbounds <- getBounds(times, experiment, subCustom)
                reference <- data.frame(tas[rbounds[1]:rbounds[2], locations])
                reference <- apply(series, 1:2, function(element){
                        return((element * 9/5) - 459.67)
                })
        }

        # Prepare return value
        ret <- list(locations = locations,
                    bounds = bounds,
                    series = series,
                    times = times,
                    dates = dates,
                    reference = reference)
        return(ret)
}

#' Find closest grid point to a city location
#'
#' This function identifies the closest grid points in a climate model to a
#'    community based on the community's latitude and longitude using the
#'    Pythagorean theorem.
#'
#' @param city A numeric vector containing the city's ID, latitude, and
#'    longitude, in that order.
#' @param latlong A dataframe of latitude and longitude pairings for each
#'    climate grid cell location, with latitudes in the first column and
#'    longitudes in the second column.
#'
#' @return An index corresponding to the column in the climate projections
#'    dataframe for that climate model that is closest to the city
#'    coordinates.
closest_point <- function(city, latlong){
        latitude <- as.double(city[2])
        longitude <- 360 - as.double(city[3])
        aSQ <- abs(latlong[,1] - latitude) ^ 2
        bSQ <- abs(latlong[,2] - longitude) ^ 2
        cSQ <- aSQ + bSQ
        c <- sqrt(cSQ)
        smallest <- min(c)
        index <- match(smallest, c)
        return(index)
}

#' Acquire boundaries of time series data
#'
#' @param times A dataframe containing the time data for one of the
#'    climate model ensemble's projection. Read in by \code{processEnsemble}.
#' @param experiment Character string of the experiment of
#'    interest. Possible variables are "historical" or "rcp85".
#' @param custom An object name for the 'custom` data list. This parameter is
#'    passed through from \code{gen_hw_set} and includes user specifications
#'    for, if specified as other than the default, an alternative function to
#'    use to identify heatwaves, alternative upper and lower year boundaries
#'    for the projection period of the heatwave datasets being generated,
#'    alternative upper and lower year boundaries for the reference period
#'    to be used when measuring all heatwave characteristics related to
#'    relative, rather than absolute, temperature, and the percentile
#'    threshold to use when defining heatwaves.
#'
#' @return A numeric vector containing the number of days spanned by the
#'    time period, the lower bound of the experiment time
#'    period as an index specifying the relevant row of the climate projection
#'    data; and an upper bound of the experiment time period as an index
#'    specifying the relevant row of the climate projection data.
#'
#' @note This function is customizable.
# TODO: See if it is possible to simplify this function by using data from the global carrier instead
# of custom
getBounds <- function(times, experiment, custom){
        # Set boundaries
        start <- 0
        end <- 0
        if (experiment == 'historical'){
                if(FALSE %in% custom[["getBounds"]]){ # `dataBoundaries` choice
                        start <- match(1981, times[,2])

                        #'end' index of the historical experiment has to be
                        #' matched from back to front. This is because the
                        #' data does/may not exceed year 2005. We wish to set
                        #' the end bound to the first day of 2004 instead.
                        # The match function alone will acquire the index of
                        # the first day of 2004, even though we want all days
                        # in 2004.
                        end <- length(times[,1]) -
                                (match(2004, rev(times[,2])) - 1)

                } else {
                        customizeHistorical <- custom[["getBounds"]]
                        lower <- customizeHistorical[1]
                        upper <- customizeHistorical[2]
                        start <- match(lower, times[,2])
                        end <- length(times[,1]) -
                                (match(upper, rev(times[,2])) - 1)
                }
        } else if (experiment == 'rcp'){
                if(FALSE %in% custom[["getBounds"]]){
                        start <- match(2061, times[,2])
                        end <- match(2081, times[,2]) - 1
                } else {
                        customizeRCP <- custom[["getBounds"]]
                        lower <- customizeRCP[3]
                        upper <- customizeRCP[4]
                        start <- match(lower, times[,2])
                        end <- match((upper + 1), times[,2]) - 1
                }
        }
        size <- end - (start - 1)
        return(c(start, end, size))
}

#' Determine dates for the requested time period.
#'
#' Acquire the dates spanning the desired time period of the ensemble
#'
#' @param times A dataframe containing the time data for one of the
#'    climate model ensemble's projection.
#' @param bounds A numeric vector with the desired time boundaries of the
#'    ensemble.
#'
#' @return A vector of dates formatted as year-month-day (%Y-%m-%d) spanning
#'    the desired time boundaries.
formDates <- function(times, bounds){
        start <- bounds[1]
        end <- bounds[2]
        dateComponents <- data.frame(times[start:end, 2:4])
        dates <- paste(dateComponents[,1],
                       dateComponents[,2],
                       dateComponents[,3],
                       sep = "-")
        dates <- as.Date(dates)
        return(dates)
}
