#' Create heatwave dataframe for the given ensemble
#'
#' @param ensemble Character string that gives the absolute file path
#'    for the directory with a particular ensemble member of a climate
#'    model projection.
#' @param thresholds [What is this?]
#' @param global List of global parameters generated by listGlobal.
#' @param custom List of custom parameters generated by listCustom.
#'
#' @return [What does this function return?]
formHwFrame <- function(ensemble, thresholds, global, custom){
        # Acquire list of heatwave dataframes for each city
        hwDataframeList <- apply(data.frame(thresholds), 1, createCityProcessor(global), ensemble, custom)

        # Combine the heatwave dataframes contained in hwDataframeList into a single dataframe
        hwFrame <- consolidate(hwDataframeList)

        return(hwFrame)
}

#' Identify and aggregate heatwaves for a particular city
#'
#' @param global List of global parameters generated by listGlobal.
#' @param custom List of custom parameters generated by listCustom.
#'
#' @return List with all heatwaves for the cities of interest
#'    for a climate projection. (is this right?)
createCityProcessor <- function(global, custom){
        i <- 1
        function(threshold, ensemble, custom){
                city <- as.character(global$cities[i,1])
                cat("Creating heatwave dataframe ~~ City: ", city, " ~~ City Number: ", i, " ~~ Cutoff: ", threshold, "\n")

                datafr <- data.frame(ensemble$dates, ensemble$series[,i])

                # Identify all heatwaves for the given city
                heatwaves <- IDheatwaves(city, threshold, 2, datafr, global, custom)

                # Aggregate heatwaves for the given city
                hwDataframeList <- createHwDataframe(city = city, threshold = threshold, heatwaves = heatwaves, ensemble = ensemble, i = i, global = global, custom = custom)

                i <<- i + 1
                return(hwDataframeList)
        }
}

#' Stitch all heatwave lists together
#'
#' @param hwDataframeList [What is this?]
#'
#' @return Dataframe with all heatwaves for the cities of interest
#'    for a climate projection.
consolidate <- function(hwDataframeList){
        all <- hwDataframeList[[1]]
        for(i in 2:length(hwDataframeList)){
                all <- rbind(all, hwDataframeList[[i]])
        }
        return(all)
}
