# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Identify heatwaves that are a certain number of days long
#'
#' @param heatwaveLength Number of days that a heatwave lasts under the user's definition
#' @param tempsExceedingCutoff A vector of 1s and 0s that is the size of the number of days in the time series.
#' 1 means the temperature for that day exceeds the calculated threshold. 0 means it does not exceed the threshold.
#'
#' @return A dataframe containing information about the heatwaves for this series. It contains three columns with
#' names "hw", "hw.number", and "first.hw.day" respectively.
#' @export
IDHeatwavesCPP <- function(heatwaveLength, tempsExceedingCutoff) {
    .Call('futureheatwaves_IDHeatwavesCPP', PACKAGE = 'futureheatwaves', heatwaveLength, tempsExceedingCutoff)
}

#' Helper function for IDHeatwavescpp that addes entries to the data structures that track
#' heatwave information
#'
#' @param index An index into the various
#' @param hwSize Size of the heatwave to be added.
#' @param hwCounter Current number of heatwaves.
#' @param hw A reference of the vector that contains the heatwaves
#' @param hwNumber A reference of the vector that contains the heatwave numbers.
#' @param firstHwDay A reference of the vector that contains the first day the heatwave occurred.
#'
#' @export
storeHeatwaveEntry <- function(index, hwSize, hwCounter, hw, hwNumber, firstHwDay) {
    invisible(.Call('futureheatwaves_storeHeatwaveEntry', PACKAGE = 'futureheatwaves', index, hwSize, hwCounter, hw, hwNumber, firstHwDay))
}

#' Helper function that adds zeroes to the data structures that track heatwave information
#'
#' @param potentialHeatwave Size of the potential heatwave that turned out not to be a heatwave.
#' @param hw A reference of the vector that contains the heatwaves
#' @param hwNumber A reference of the vector that contains the heatwave numbers.
#' @param firstHwDay A reference of the vector that contains the first day the heatwave occurred.
#'
#' @export
storeZeroes <- function(index, potentialHeatwave, hw, hwNumber, firstHwDay) {
    invisible(.Call('futureheatwaves_storeZeroes', PACKAGE = 'futureheatwaves', index, potentialHeatwave, hw, hwNumber, firstHwDay))
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('futureheatwaves_RcppExport_registerCCallable', PACKAGE = 'futureheatwaves')
})
